spring:
  application:
    name: todolist
  datasource:
    url: jdbc:h2:mem:tododb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
api:
  endpoint:
    base-url: /api/v1

